export const ONE_SECOND = 1000
export const ONE_MINUTE = ONE_SECOND * 60
export const MINUTES_PER_TOMATO = 25
export const MINUTES_FOR_BREAK = 5
export const MINUTES_FOR_LONG_BREAK = 15
export const WORK_TIME = MINUTES_PER_TOMATO * ONE_MINUTE
export const BREAK_TIME = MINUTES_FOR_BREAK * ONE_MINUTE
export const LONG_BREAK_TIME = MINUTES_FOR_LONG_BREAK * ONE_MINUTE
